server:
  port: 8001
spring:
  application:
    name: demo7
  #配置rabbitMq 服务器
  rabbitmq:
    host: 192.168.221.128
    port: 5672
    username: chu
    password: 102502
#    #虚拟host 可以不设置,使用server默认host
#    virtual-host: JCcccHost
